version: '3'

services:
  database:
    container_name: database
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: hackyeah
    volumes:
      - ./persistent/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: zaq1@WSX
      PMA_ABSOLUTE_URI: /
    ports:
      - "8081:80"